version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bookmark_saver
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped

  backend:
    image: ${DOCKER_HUB_USERNAME}/bookmark-saver-backend:latest
    environment:
      NODE_ENV: production
      PORT: 5001
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: bookmark_saver
      DB_USER: admin
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRE: 7d
    ports:
      - "5001:5001"
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    image: ${DOCKER_HUB_USERNAME}/bookmark-saver-frontend:latest
    environment:
      REACT_APP_API_URL: http://localhost:5001/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
